name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Create .env file
        run: |
          cat <<EOF > .env
          VITE_CLERK_PUBLISHABLE_KEY='${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}'
          VITE_FIREBASE_API_KEY='${{ secrets.VITE_FIREBASE_API_KEY }}'
          VITE_FIREBASE_AUTH_DOMAIN='${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}'
          VITE_FIREBASE_PROJECT_ID='${{ secrets.VITE_FIREBASE_PROJECT_ID }}'
          VITE_FIREBASE_STORAGE_BUCKET='${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}'
          VITE_FIREBASE_MESSAGING_SENDER_ID='${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}'
          VITE_FIREBASE_APP_ID='${{ secrets.VITE_FIREBASE_APP_ID }}'
          VITE_FIREBASE_MEASUREMENT_ID='${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}'
          VITE_GEMINI_API_KEY='${{ secrets.VITE_GEMINI_API_KEY }}'
          EOF

      - name: Verify .env keys
        run: |
          echo "Verifying .env variables..."
          grep -o '^[^=]*' .env

      - name: Build project
        run: pnpm build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AI_MOCK_INTERVIEW_TYPESRCIPT }}"
          channelId: live
          projectId: ai-mock-interview-typesrcipt
